### ISSUE TITLE
Can't use "fill" property

### ISSUE THREAD

**Issue by ChristofferOakDigital** [Oak-Digital/nextjs-strapi-image#1]
You can't use the fill prop since NEXT only allows either width or fill.

Error:
Unhandled Runtime Error
Error: Image with src ["http://127.0.0.1:1337/uploads/Group_695_0070fbbd68.jpg"](http://127.0.0.1:1337/uploads/Group_695_0070fbbd68.jpg) has both "width" and "fill" properties. Only one should be used.

**Comment by Alexnortung** [comment]
Done, this has been fixed in `v0.0.2`
